### ISSUE TITLE
ionic serve throws "ReferenceError: facebookConnectPlugin is not defined"

### ISSUE THREAD

**Issue by lordlothar99** [SiddharthaRRamesh/ionic-starter-oauth#12]
Hi
I followed your steps, but unfortunately when I use `ionic serve`, and then I click on "Facebook", I get this error : 

```
0     863751   error    ReferenceError: facebookConnectPlugin is not defined
    at Object.login (http://localhost:8100/lib/ionic/js/ng-cordova.js:1577:11)
    at Scope.$scope.fbLogin (http://localhost:8100/js/app.js:42:22)
    at $parseFunctionCall (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20124:18)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:50863:9
    at Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22178:28)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22276:23)
    at HTMLButtonElement.<anonymous> (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50862:13)
    at HTMLButtonElement.eventHandler (http://localhost:8100/lib/ionic/js/ionic.bundle.js:10823:21)
    at triggerMouseEvent (http://localhost:8100/lib/ionic/js/ionic.bundle.js:2811:7)
    at tapClick (http://localhost:8100/lib/ionic/js/ionic.bundle.js:2800:3)
```

**Comment by srameshr** [comment]
Try running it on a device and not on your desktop / laptop browser. 

```
ionic run android
```

<b>OR</b>

```
ionic run ios
```

This would do.
